# Generated by Django 4.0.4 on 2022-06-16 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.countries')),
            ],
            options={
                'db_table': 'manufacturers',
            },
        ),
        migrations.CreateModel(
            name='Types',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'types',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=30)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10000)),
                ('description', models.TextField(blank=True)),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.manufacturers')),
            ],
            options={
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='PokemonWeaknesses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.products')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.types')),
            ],
            options={
                'db_table': 'pokemon_weaknesses',
            },
        ),
        migrations.CreateModel(
            name='PokemonTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.products')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.types')),
            ],
            options={
                'db_table': 'pokemon_types',
            },
        ),
        migrations.CreateModel(
            name='Pictures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.ImageField(upload_to='pictures/pokemons/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.products')),
            ],
            options={
                'db_table': 'pictures',
            },
        ),
        migrations.CreateModel(
            name='ManufacturersNumbers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.manufacturers')),
            ],
        ),
        migrations.CreateModel(
            name='ManufacturersEmails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.manufacturers')),
            ],
        ),
        migrations.CreateModel(
            name='Evolutions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pre_evolve_f', models.IntegerField(default=0)),
                ('pre_evolve_s', models.IntegerField(default=0)),
                ('next_evolve_f', models.IntegerField(default=0)),
                ('next_evolve_s', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.products')),
            ],
            options={
                'db_table': 'evolutions',
            },
        ),
    ]
