# Generated by Django 4.0.4 on 2022-06-16 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='countries',
            options={'verbose_name_plural': 'Countries'},
        ),
        migrations.AlterField(
            model_name='manufacturersnumbers',
            name='number',
            field=models.CharField(max_length=20),
        ),
    ]
